spring:
  datasource:
    url: jdbc:h2:mem:cos;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    username: admin
    password:
  h2:
    console:
      path: /db
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
